-- AlterTable
ALTER TABLE "Lesson" ALTER COLUMN "date" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "SchoolHour" ALTER COLUMN "startTime" SET DATA TYPE TIME,
ALTER COLUMN "endTime" SET DATA TYPE TIME;

-- AlterTable
ALTER TABLE "SchoolYear" ALTER COLUMN "startDate" SET DATA TYPE DATE,
ALTER COLUMN "endDate" SET DATA TYPE DATE;
